### ISSUE TITLE
Data should be stripped away from data URLs before being stored

### ISSUE THREAD

**Issue by motin** [mozilla/openwpm-webext-instrumentation#23]
* **I'm submitting a ...**
[X] bug report
[ ] feature request
[ ] question about the decisions made in the repository
[ ] question about how to use this project

* **Summary**
Navigating to a page which uses [data URLs](https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/Data_URIs) results in http request log calls which includes the full data url, including the contents of the resource (usually base64-encoded).

* **Other information**
Data URLs contain `data:[<mediatype>][;base64],<data>`. If neither `saveAllContent` nor `saveJavascript` is true, the `<data>` portion should be stripped away. Possible replaced by a certain sequence of characters (maybe `<data-removed>`) to indicate that the data has been removed.

**Comment by englehardt** [comment]
I agree that we should strip the content here, but I don't think we should tie it into `saveAllContent` or `saveJavascript`. I'd like to keep these config parameters strictly related to saving response body content such that we can expand them as described in #24.

Instead, I suggest we create a new config parameter titled: `saveDataUrls` that controls this. When this is set to true we save the full URL and when it's set to false (the default) we strip the content. What do you think about saving the hash of the current data URL, as opposed to saving a generic `<data-removed>`. This way we at least know something about the uniqueness and reuse of the truncated URLs, even if we don't know their content.

**Comment by motin** [comment]
> I'd like to keep these config parameters strictly related to saving response body content such that we can expand them as described in #24. Instead, I suggest we create a new config parameter titled: saveDataUrls that controls this. When this is set to true we save the full URL and when it's set to false (the default) we strip the content.

+1 but I propose to call it `stripDataUrlData` and simply let it control whether or not to strip the `<data>` portions from all encountered data URLs.

Thinking about the `saveAllContent` etc switches and the saving of data URL content, it may already be supported today, since data URLs are accompanied by corresponding "fake" web request events, so their content should already be saved and hashed if config so allows.

> Alternatively, if we do land #24 we could add data_url as a new resource type option that could be included in the saveContent array.

-1 - we should keep the resource types list to match https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/webRequest/ResourceType, and given the "fake" web request events mentioned above, the resource type for these request ought to correspond to their actual resource type so I think we are already golden here. 

> What do you think about saving the hash of the current data URL, as opposed to saving a generic <data-removed>. This way we at least know something about the uniqueness and reuse of the truncated URLs, even if we don't know their content.

+1 but I see it as an enhancement rather than a basic requirement for the stripping-data-from-data-urls feature.

**Comment by englehardt** [comment]
> +1 but I see it as an enhancement rather than a basic requirement for the stripping-data-from-data-urls feature. Maybe we can file a separate issue for it? It could be configured behind hashDataUrlData

Totally fine punting to a future issue, but I don't think it's worth making a new config flag for it. The increase in size is relatively small (we don't need a big hash). Mind to file the follow-up when you fix this?

**Comment by motin** [comment]
Follow-up issues: #33, #34
