### ISSUE TITLE
Record web navigation onBeforeNavigate timestamp and event ordinal

### ISSUE THREAD

**Issue by motin** [mozilla/openwpm-webext-instrumentation#30]
* **I'm submitting a ...**
[ ] bug report
[x] feature request
[ ] question about the decisions made in the repository
[ ] question about how to use this project

* **Summary**

This issue stems from the discussion regarding timing issues related to matching web navigation events with request and js log calls. These can be partially mitigated by instrumenting more of [the web navigation life-cycle](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/webNavigation) as mentioned in https://github.com/mozilla/openwpm-webext-instrumentation/issues/9

Currently, only the web navigation onCommitted timestamp and event ordinal is recorded, making it hard to assign the request events that occur before it to the correct web navigation event.

* **Other information**

A typical "Visit Example.com and then click on the `More information` link" yields the following event sequence, showing how onBeforeNavigate makes it easier to assign the events to the proper web navigation event:
```
Object { type: "navigations", payload: {…}, tabActiveDwellTime: 5250 } <-- onBeforeNavigate for navigation 1
​Object { type: "http_requests", payload: {…}, tabActiveDwellTime: 5250 }
​Object { type: "navigations", payload: {…}, tabActiveDwellTime: 5500 } <-- onCommitted for navigation 1
​Object { type: "http_responses", payload: {…}, tabActiveDwellTime: 5500 }
​Object { type: "http_requests", payload: {…}, tabActiveDwellTime: 5750 }
​Object { type: "http_responses", payload: {…}, tabActiveDwellTime: 5750 }
​Object { type: "navigations", payload: {…}, tabActiveDwellTime: 20000 } <-- onBeforeNavigate for navigation 2
​Object { type: "http_requests", payload: {…}, tabActiveDwellTime: 20000 }
​Object { type: "http_redirects", payload: {…}, tabActiveDwellTime: 20500 }
​Object { type: "http_requests", payload: {…}, tabActiveDwellTime: 20500 }
​Object { type: "navigations", payload: {…}, tabActiveDwellTime: 21250 } <-- onCommitted for navigation 2
​Object { type: "http_requests", payload: {…}, tabActiveDwellTime: 21250 }
​Object { type: "http_requests", payload: {…}, tabActiveDwellTime: 21250 }
​Object { type: "http_requests", payload: {…}, tabActiveDwellTime: 21250 }
​Object { type: "http_requests", payload: {…}, tabActiveDwellTime: 21250 }
​Object { type: "http_requests", payload: {…}, tabActiveDwellTime: 21250 }
```

**Comment by motin** [comment]
As a bonus, the `parentFrameId` will get properly stored. The current instrumentation incorrectly tries to read a variant of this attribute from the onCommitted event, but it only exists in the onBeforeNavigate event.

**Comment by englehardt** [comment]
In #9 you wrote
> Hopefully, the events can be fully assignable to a specific web navigation event based on heuristics involving frame id, transition type and ideally #10

It seems like this will solve that, even without #10. Are there still requests that will be out of order?

**Comment by motin** [comment]
This solves the `heuristics involving frame id` part of the above, but since requests and responses from the previous navigation may still be in flight when a user clicks a link, there is a sizable risk that those in-flight events will be attributed to the new navigation (for instance an async response that was received after the new onBeforeNavigate, but stemmed from an older request).

Also, as a side note: requests from service workers are not even attributed a tabId/frameId, so they are not even assignable to a certain tab/frame/navigation currently: https://bugzilla.mozilla.org/show_bug.cgi?id=1503898
